version: '3'
services:
#container que faz a mesma coisa sem utilizar o Dockerfile
  php:
    container_name: app_php
    image: php:8.2-cli
    ports:
      - 8029:80
    volumes:
      - .:/usr/src/www
    working_dir: /usr/src/www
    command: php -S 0.0.0:80
  app_php1:
    container_name: app_php_1
    build: 
      context: .
      dockerfile: Dockerfile
    image: desafio_php
    ports: 
    - 8030:80
    networks:
      - desafio_php
    volumes:
      - .:/usr/src/www
  app_php2:
    container_name: app_php_2
    build: 
      context: .
      dockerfile: Dockerfile
    image: desafio_php
    ports: 
    - 8031:80
    networks:
      - desafio_php
    volumes:
      - .:/usr/src/www
  proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8032:80
    networks:
      - desafio_php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app_php

networks:
  desafio_php:
    driver: bridge