version: '3'
services:
  app_php1:
    container_name: app_php_1
    build: .
    ports: 
    - 8030:80
    networks:
      - desafio_php
    volumes:
      - .:/usr/src/www
  app_php2:
    container_name: app_php_2
    build: .
    ports: 
    - 8031:80
    networks:
      - desafio_php
    volumes:
      - .:/usr/src/www
  proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8032:80
    networks:
      - desafio_php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app_php

networks:
  desafio_php:
    driver: bridge